dbt_proj1: # this needs to match the profile in your dbt_project.yml file
  target: local
  outputs:
    local:
      type: bigquery
      method: oauth
      project: uplifted-earth-461819-f7 # Replace this with your project id
      location: us-central1 # Replace this with your locationxx
      dataset: db_dbt_local # Replace this with dbt_your_name, e.g. dbt_bilbo
      impersonate_service_account: sa-dbt@uplifted-earth-461819-f7.iam.gserviceaccount.com # replace with service account
    
    slim_ci:
      type: bigquery
      method: oauth
      project: uplifted-earth-461819-f7 # Replace this with your project id
      dataset: db_dbt_slim_ci # Replace this with dbt_your_name, e.g. dbt_bilbo

    dev:
      type: bigquery
      method: oauth
      project: uplifted-earth-461819-f7 # Replace this with your project id
      dataset: dbt_ds_dev # Replace this with dbt_your_name, e.g. dbt_bilbo